all:
    -xcopy /y/d/e/i "..\..\..\WebKitLibraries\win\tools" "$(WEBKITLIBRARIESDIR)\tools"
    touch "$(WEBKITOUTPUTDIR)\buildfailed"
    bash build-generated-files.sh "$(WEBKITOUTPUTDIR)" "$(WEBKITLIBRARIESDIR)"
    -mkdir 2>NUL "$(WEBKITOUTPUTDIR)\include\TiCore"
    xcopy /y /d "..\..\API\APICast.h" "$(WEBKITOUTPUTDIR)\include\TiCore"
    xcopy /y /d "..\..\API\Ti.h" "$(WEBKITOUTPUTDIR)\include\TiCore"
    xcopy /y /d "..\..\API\TiBase.h" "$(WEBKITOUTPUTDIR)\include\TiCore"
    xcopy /y /d "..\..\API\TiContextRef.h" "$(WEBKITOUTPUTDIR)\include\TiCore"
    xcopy /y /d "..\..\API\TiObjectRef.h" "$(WEBKITOUTPUTDIR)\include\TiCore"
    xcopy /y /d "..\..\API\TiStringRef.h" "$(WEBKITOUTPUTDIR)\include\TiCore"
    xcopy /y /d "..\..\API\TiStringRefCF.h" "$(WEBKITOUTPUTDIR)\include\TiCore"
    xcopy /y /d "..\..\API\TiStringRefBSTR.h" "$(WEBKITOUTPUTDIR)\include\TiCore"
    xcopy /y /d "..\..\API\TiValueRef.h" "$(WEBKITOUTPUTDIR)\include\TiCore"
    xcopy /y /d "..\..\API\TiCore.h" "$(WEBKITOUTPUTDIR)\include\TiCore"
    xcopy /y /d "..\..\API\TiRetainPtr.h" "$(WEBKITOUTPUTDIR)\include\TiCore"
    xcopy /y /d "..\..\API\OpaqueTiString.h" "$(WEBKITOUTPUTDIR)\include\TiCore"
    xcopy /y /d "..\..\API\WebKitAvailability.h" "$(WEBKITOUTPUTDIR)\include\TiCore"
    -del "$(WEBKITOUTPUTDIR)\include\private\TiCore\stdbool.h" "$(WEBKITOUTPUTDIR)\include\private\TiCore\stdint.h"
    -del "$(WEBKITOUTPUTDIR)\buildfailed"

clean:
    -del "$(WEBKITOUTPUTDIR)\buildfailed"
    -del /s /q "$(WEBKITOUTPUTDIR)\include\TiCore\TiCore"
    -del /s /q "$(WEBKITOUTPUTDIR)\obj\TiCore\DerivedSources"
