language: objective-c
osx_image: xcode7.1
env:
 global:

before_install:
 - gem install xcpretty
 
install:

script:
 # Build WTF
 - rm -rf Build
 - rm -rf WTF/build
 - mkdir Build
 - set -o pipefail && xcodebuild -project WTF/WTF.xcodeproj -sdk iphonesimulator -configuration "Release" -target WTF clean | xcpretty -c
 - set -o pipefail && xcodebuild -project WTF/WTF.xcodeproj -sdk iphoneos -configuration "Release" -target WTF clean | xcpretty -c
 - set -o pipefail && xcodebuild -project WTF/WTF.xcodeproj -sdk iphonesimulator -configuration "Release" -target WTF OTHER_CFLAGS="-fembed-bitcode" CLANG_ENABLE_MODULE_DEBUGGING=NO GCC_PRECOMPILE_PREFIX_HEADER=NO DEBUG_INFORMATION_FORMAT="DWARF with dSYM"| xcpretty -c
 - set -o pipefail && xcodebuild -project WTF/WTF.xcodeproj -sdk iphoneos -configuration "Release" -target WTF OTHER_CFLAGS="-fembed-bitcode" CLANG_ENABLE_MODULE_DEBUGGING=NO GCC_PRECOMPILE_PREFIX_HEADER=NO DEBUG_INFORMATION_FORMAT="DWARF with dSYM"| xcpretty -c
 - lipo WTF/build/Release-iphonesimulator/libWTF.a WTF/build/Release-iphoneos/libWTF.a -create -output Build/libWTF.a
 - xcrun -sdk iphoneos lipo -info Build/libWTF.a 

 - mkdir Build/PRIVATE_HEADERS
 - cp -R WTF/build/Release-iphoneos/usr/local/include/ Build/PRIVATE_HEADERS

 - rm -rf WTF/build

 # Build TiJSCore
 - rm -rf JavaScriptCore/build
 - set -o pipefail && xcodebuild -project JavaScriptCore/JavaScriptCore.xcodeproj -sdk iphonesimulator -configuration "Release" -target JavaScriptCore clean | xcpretty -c
 - set -o pipefail && xcodebuild -project JavaScriptCore/JavaScriptCore.xcodeproj -sdk iphoneos -configuration "Release" -target JavaScriptCore clean | xcpretty -c
 - set -o pipefail && xcodebuild -project JavaScriptCore/JavaScriptCore.xcodeproj -sdk iphonesimulator -configuration "Release" -target JavaScriptCore OTHER_CFLAGS="-fembed-bitcode" CLANG_ENABLE_MODULE_DEBUGGING=NO GCC_PRECOMPILE_PREFIX_HEADER=NO DEBUG_INFORMATION_FORMAT="DWARF with dSYM"| xcpretty -c
 - set -o pipefail && xcodebuild -project JavaScriptCore/JavaScriptCore.xcodeproj -sdk iphoneos -configuration "Release" -target JavaScriptCore OTHER_CFLAGS="-fembed-bitcode" CLANG_ENABLE_MODULE_DEBUGGING=NO GCC_PRECOMPILE_PREFIX_HEADER=NO DEBUG_INFORMATION_FORMAT="DWARF with dSYM"| xcpretty -c
 - lipo JavaScriptCore/build/Release-iphonesimulator/libJavaScriptCore.a JavaScriptCore/build/Release-iphoneos/libJavaScriptCore.a -create -output Build/libTiCore.a
 - xcrun -sdk iphoneos lipo -info Build/libTiCore.a 

 - mkdir Build/PUBLIC_HEADERS
 - cp -R JavaScriptCore/build/Release-iphoneos/usr/local/include/ Build/PUBLIC_HEADERS
 - cp -R JavaScriptCore/build/Release-iphoneos/PRIVATE_HEADERS/ Build/PRIVATE_HEADERS

 - rm -rf JavaScriptCore/build

 - ls -la
 - ls -la Build/
 - mv Build libTiCore
 - zip -r libTiCore.zip libTiCore
 
after_success:

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: SqJbA96CYvtXxchrg14+6NSMZCgkDxjADR8iRcR/R4PnUEkFJByChgsYoy8ER5z8CNL51YNj8Lxkez/NjwjeU0Qkww2gXpepiM8HCMwpo25hjrjHqz83bp712PI2G4zaS72E+Pu2kahhOTno8yum3e+4hxySI9cegpXbBgrg7po=
  file: $TRAVIS_BUILD_DIR/libTiCore.zip
  on:
    all_branches: true
    tags: true
